#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"/..

function eprintln() {
  >&2 echo "$1"
}

eprintln "Formatting sources"
cargo fmt -- --check

eprintln "Linting sources"
cargo clippy --all-targets -- -D warnings

eprintln "Running tests (default)"
cargo test
eprintln "Running tests (no features)"
cargo test --no-default-features
eprintln "Running tests (cli)"
cargo test --no-default-features --features cli

eprintln "Building documentation"
cargo doc --no-deps --lib

eprintln "Running mdbook integration test"
./integration/scripts/check
