#!/bin/bash

set -exuo pipefail

cd "$(dirname "$0")"/..

rustup component add rustfmt clippy

if ! cargo audit --version; then
  cargo install cargo-audit --force
fi
if ! mdbook --version; then
  cargo install mdbook --force
fi
