#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"/..

function eprintln() {
  >&2 echo "$1"
}

VERSION="0.4.35"

eprintln "Checking if mdbook $VERSION is installed"
if [[ "$(mdbook --version)" != "mdbook v$VERSION" ]]; then
  eprintln "Installing mdbook $VERSION"
  cargo install mdbook --version "$VERSION" --force
fi
eprintln "mdbook $VERSION is installed"
