#!/bin/bash

# Install everything for development/CI
#
# Does not include offline node development stack (i.e. yarn)

set -exuo pipefail

cd "$(dirname "$0")"/..

rustup component add rustfmt clippy

./scripts/install-mdbook
