#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"/..

function eprintln() {
  >&2 echo "$1"
}

eprintln "Generating styles"
pushd compile_assets
yarn run build
popd

eprintln "Installing mdbook-admonish (to system)"
cargo install --path . --force

pushd book
eprintln "Installing mdbook-admonish (to book)"
mdbook-admonish install .

eprintln "Building book"
mdbook build
popd

eprintln "Book generated at ./book/book/index.html"
